import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.className} max-w-1440px`}>
				<nav className='flex items-center  p-2 gap-2'>
					<Link href='/'>Timestamps</Link>
					<Link href='/cars'>Cars</Link>
				</nav>
				{children}
			</body>
		</html>
	)
}
